### ISSUE TITLE
Successful/Unsuccessful payment pages for payment gateway integration

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/MAVN.FrontEnd.CustomerWebsite#6]
We need to host 2 pages:
1. For successful payment
2. For not successful payment
Payment gateway will redirect to one of those pages after payment process is completed depending on payment transaction processing result.

Page must parse query parameters and extract 'payment' parameter.
Endpoint implemented in OpenMAVN/MAVN.Service.PartnerAPI#1 must be called with this parameter

**Comment by vitaliidasaev** [comment]
@kslonik21 please comment to be assigned

**Comment by kslonik21** [comment]
Assign to me

**Comment by vitaliidasaev** [comment]
updated settings values:
* PaymentManagementService-PaymentSuccessUrlTemplate
https://customer-website.mavn.ch/en/transaction-status?state=success&paymentRequestId={0}
* PaymentManagementService-PaymentFailUrlTemplate
https://customer-website.mavn.ch/en/transaction-status?state=fail&paymentRequestId={0}

**Comment by vitaliidasaev** [comment]
added settings to MAVN.Frontend.CustomerWebsite:
"PartnerApiUrl": "https://partner-api.mavn.ch"
